config/routes.rb
Rails.application.routes.draw do
  default_url_options host: 'localhost'
  devise_for :users

  root 'posts#index'
  get '/show/:id' => 'profiles#show', as: 'profile'
  get '/moderator/:id' => 'profiles#moderator', as: 'moderator'
  get '/del_moderator/:id' => 'profiles#del_moderator', as: 'del_moderator'
  get '/ban/:id' => 'profiles#ban', as: 'ban'
  get '/unban/:id' => 'profiles#unban', as: 'unban'
  get '/index/:id' => 'table_mmr#index', as: 'table_mmr'

  resources :posts do
    resources :likes
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader

  belongs_to :user
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :title, :summary, :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :posts, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :validatable

  def account_active?
    ban.nil?
  end

  def active_for_authentication?
    super && account_active?
  end

  def inactive_message
    account_active? ? super : :locked
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  # skip_before_action :verify_authenticity_token

  add_flash_types :success, :danger, :info, :warning
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def destroy
    @comment = Comment.find(params[:post_id])
    if @comment.present?
      @comment.destroy
      redirect_to post_path, notice: 'comment delete'
    else
      redirect_to post_path, notice: 'comment not exists'
    end
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.email = current_user.email

    if @comment.save
      redirect_to post_path(@post), notice: 'comment created'
    else
      redirect_to post_path(@post), notice: "comment don't created"
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:email, :body)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_like, only: %i[create destroy count_like]

  def destroy
    @like = @post.likes.find(params[:id])
    if @like.present?
      @like.destroy
      count_like
      redirect_to post_path(@post), notice: 'dislike'
    else
      redirect_to post_path(@post), notice: 'dislike error'
    end
  end

  def create
    @like = @post.likes.new(user_id: current_user.id)
    count_like
    if @like.save
      redirect_to post_path(@post), notice: 'like'
    else
      redirect_to post_path(@post), notice: 'like error'
    end
  end

  private

  def set_like
    @post = Post.find(params[:post_id])
  end

  def count_like
    @post.update(count_like: @post.likes.count)
    @post.count_like = @post.likes.count
    @post.save
  end

  def like_params
    params.require(:like).permit(:user_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  def index
    @posts = Post.all
  end

  def show
    @user_owner = User.find(@post.user_id)
  end

  def new
    @post = current_user.posts.build
  end

  def edit; end

  def create
    @post = current_user.posts.create(post_params)
    @post.update(count_like: 0)

    if @post.update(post_params)
      redirect_to @post, success: 'Article updated successfully'
    else
      render :new, error: 'The article has not been updated'
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post, success: 'Article updated successfully'
    else
      render :edit, error: 'The article has not been updated'
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  private

  def set_post
    @post = Post.find(params[:id])
    @user = current_user
  end

  def post_params
    params.require(:post).permit(:title, :summary, :body, :user_id, :draft, :image)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user

  def show
    @posts = Post.where(user_id: @user.id)
    @my_mmr = 0
    @posts.each do |post|
      @my_mmr += post.likes.count
    end
  end

  def moderator
    return unless user_signed_in? && current_user.rank == 2

    case @user.rank
    when 0
      @user.update(rank: 1)
      @user.rank = 1
      @user.save
      redirect_to profile_path(@user.id), success: 'success'
    when 1
      redirect_to profile_path(@user.id), error: 'error'
    end
  end

  def del_moderator
    return unless user_signed_in? && current_user.rank == 2

    case @user.rank
    when 1
      @user.update(rank: 0)
      @user.rank = 0
      @user.save
      redirect_to profile_path(@user.id), success: 'success'
    when 0
      redirect_to profile_path(@user.id), error: 'error'
    end
  end

  def ban_time(time)
    Time.zone.now + Time.zone.at(time)
  end

  def ban
    return unless user_signed_in?

    @time_zone = Time.zone.at(ban_time(3600 * 24 * 30))
    @user.update(ban: @time_zone)
    @user.ban = @time_zone
    @user.save
    redirect_to profile_path(@user.id), success: "success, the user:#{@user.email} received a ban until #{@user.ban}"
  end

  def unban
    return unless user_signed_in?

    @user.update(ban: nil)
    @user.ban = nil
    @user.save
    redirect_to profile_path(@user.id), success: "success, the user:#{@user.email} is unban"
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/table_mmr_controller.rb
class TableMmrController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(name)
    {	success: 'alert-success',
      error: 'alert-danger',
      danger: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info' }[name.to_sym] || name
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/table_mmr_helper.rb
module TableMmrHelper
end

app/helpers/user_page_helper.rb
module UserPageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStarterProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container" style="border-bottom: 2px solid blue; background-color: #F5F5F5">
      
      <h1 class="navbar-brand" href="#">VebBlog</h1>
      <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">

        <ul class="navbar-nav mr-auto justify-content-md-between">
          <li class="nav-item active">
            <a class="nav-link" href="<%= root_path %>">All articles</a>
          </li>
          <li class="nav-item active">
            <% if user_signed_in? %>
              <%= link_to 'new article', new_post_path, class: 'btn btn-outline-primary pull-sm' %>
            <% end %>
          </li>
        </ul>

        <ul class="navbar-nav pull-xs-right">
          <% if user_signed_in? %>
            <% if current_user.rank == 2 %>
              <li class="nav-item">
                <%= link_to "Admin", profile_path(current_user.id) %>
              </li>
            <% elsif current_user.rank == 1 %>
              <li class="nav-item">
                <%= link_to "Moderator", profile_path(current_user.id) %>
              </li>
            <% end %>
            <li class="nav-item">
              <%= link_to current_user.email, profile_path(current_user.id) %>
            </li>
            <li class="nav-item">
              <%= link_to "Table mmr", table_mmr_path(current_user.id), class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign in", new_user_registration_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </nav>
    </div>

    <div class="container main">
      <div class="row">
        <div class="col-md-12">
          <% flash.each do |name, message| %>
            <div class="alert <%= bootstrap_class_for(name) %>">
              <%= message %>
            </div>
          <% end %>
        </div>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
  <div class="alert alert-danger">
    
    <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @post, html: {multipart: true} do |f| %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :summary %>
    <%= f.text_field :summary, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_field :body, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.file_field :image %>
  </div>

  <div class="form-group">
    <%= f.label 'to publish?' %><br/>
    <%= f.label :draft, "Yes", :value => "true" %>
    <%= f.radio_button :draft, false %>
    <%= f.label :draft, "No", :value => "false" %>
    <%= f.radio_button :draft, true, :checked => true%>
  </div>

  <div class="form-group">
    <%= f.submit 'Save', class: 'btn btn-primary' %>
    <%= link_to 'Back', :back, class: 'btn btn-outline-secondary' %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<article class="post">
  <section class="post-head">

    <h2><%= link_to post.title, post_path(post) %></h2>
    <smal>
      <time><%= post.created_at.to_date.strftime("%d, %B, %Y") %></time>
      <% if post.draft %>
        draft
      <% end %>
    </smal>
  </section>

  <section class="post-summary clearfix">
    <%= image_tag post.image.url(:thumb), class: 'img-thumbnail thumb' if post.image? %>
    <%= post.summary %>
  </section>
</article>
<br>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<section id='posts'>
	<%= render @posts.where(draft: :false).order(updated_at: :desc) %>
</section>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<% if current_user.id == @user_owner.id || !@post.draft? %> 
  <article class="post">
    <section class="post-head">
      <h1><%= link_to @user_owner.email, profile_path(@user_owner.id) %></h1>
      <h1><%= @post.title %></h1>
      <smal>
        <time><%= @post.created_at.to_date.strftime("%d, %B, %Y") %></time>
        <% if user_signed_in? && (current_user.rank == 2 || current_user.id == @post.user_id || (current_user.rank == 1 && @user_owner.rank == 0)) %>
  	      <%= link_to 'Edit', edit_post_path(@post) %>
  	      <%= link_to 'Destroy', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>
  	    <% end %> 
      </smal>
    </section>

    <section class="post-body">
    	<%= image_tag @post.image.url(:large), class: 'img-show' if @post.image? %>
      <%= @post.body.html_safe %>
    </section>
    <br>

    <% if user_signed_in? %>
      <% if !@post.draft? %>
        <%= form_for([@post, @post.likes.build]) do |like| %>
          <% if !@post.likes.exists?(user_id: current_user.id) %>
            <p class="form-group">
              <%= like.submit 'like', class: 'btn btn-primary' %>
               <%= @post.likes.count %>
            </p>
          <% end %>
        <% end %>
        
        <% @post.likes.where(user_id: current_user.id).each do |like| %>
          <p class="form-group">
            <%= link_to 'dislike', [like.post, like], :method => :delete, class: 'btn btn-primary' %>
              <%= @post.likes.count %>
          </p>
        <% end %>
      <% end %>
    <% end %>
    <br>

    <% if !@post.draft %>
      <h2>Comments</h2>

      <% @post.comments.each do |comment| %>
        <time><%= @post.created_at.to_date.strftime("%d, %B, %Y") %></time>
          <% if user_signed_in? && (current_user.rank == 2 || current_user.email == comment.email || (current_user.rank == 1 && @user_owner.rank == 0)) %>
            <%= link_to 'Destroy', post_comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %> 
        <p><strong><%= comment.email %></strong>: <%= comment.body %></p>
        <br>
      <% end %>

      <% if user_signed_in? %>
        <%= form_for([@post, @post.comments.build]) do |comment| %>
          
          <p class="form-group">
            <%= comment.text_field :body, class: 'form-control' %>
          </p>

          <p class="form-group">
            <%= comment.submit 'add comment', class: 'btn btn-primary' %>
          </p>
        <% end %>
      <% end %>
    <% end %>

  </article>
  <br>
<% end %>

app/views/posts/temp/_disqus.html.erb
<div id="disqus_thread"></div>
<script>
  /**
  *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
  *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables    */
  /*
  var disqus_config = function () {
  this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
  this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
  };
  */
  var disqus_config = function () {
    this.page.url = 'http://localhost.com<%= request.original_fullpath%>';  // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier = '<%= @post.id %>'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
  };

  (function() { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');
    s.src = 'https://blogveb.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/posts/temp/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

app/views/profiles/show.html.erb
<h1><%= @user.email %></h1> 
<% if user_signed_in? %>
	<% if current_user.rank == 2 %>
		<% if @user.rank == 0 %>
			<ul class="navbar-nav pull-xs-right">
				<li class="nav-item">
					<%= link_to 'make a moderator', moderator_path(@user.id) %>
				</li>
			</ul>
		<% elsif @user.rank == 1%>
			<ul class="navbar-nav pull-xs-right">
				<li class="nav-item">
					<%= link_to 'make an ordinary mortal', del_moderator_path(@user.id) %>
				</li>
			</ul>
		<% end %>
	<% end %>
	<% if current_user.rank == 2 && @user.rank != 2 || current_user.rank == 1 && @user.rank == 0%>
		<% if !@user.ban || @user.ban <= Time.zone.now %>
			<ul class="navbar-nav pull-xs-right">
				<li class="nav-item">
					<%= link_to 'ban', ban_path(@user.id) %>
				</li>
			</ul>
		<% else %>
			<ul class="navbar-nav pull-xs-right">
				<li class="nav-item">
					<%= link_to 'disban', unban_path(@user.id) %>
				</li>
			</ul>
		<% end %>
	<% end %>
<% end %>
likes: <%= @my_mmr %>
<br><br>
<% if @user.posts.where(draft: :false).count != 0 %>
	<% if user_signed_in? && @user.id == current_user.id %>
		<h2>my posts:</h2>
	<% else %>
		<h2>posts:</h2>
	<% end %>
<% end %>

<section id='posts'>
	<%= render @user.posts.where(draft: :false).order(updated_at: :desc) %>
</section>
<% if user_signed_in? && current_user.id == @user.id && @user.posts.where(draft: :true).count != 0 %>
	<section id='posts'>
		<h2>my drafts:</h2>
		<%= render @user.posts.where(draft: :true).order(updated_at: :desc) %>
	</section>
<% end %>

app/views/table_mmr/_user.html.erb
<article class='mmr'>
  <section class="post-head">
  	<% i = 1 %>
    <% users_have_posts.each do |user| %>
		<h2><%= i %>. <%= link_to user.email, profile_path(user.id) %><% if user.rank == 2 %> admin<% elsif user.rank == 1 %> moderator <% end %> </h2>
		<% temp = 0 %>
		<% user.posts.each do |post| %>
			<% temp += post.likes.count %>
		<% end %>
		<h4 style="margin-left: 1em">likes: <%= temp %></h4>
		<% i = i + 1 %>
	<% end %>
	<% users_have_not_posts.each do |user| %>
		<h2><%= i %>. <%= link_to user.email, profile_path(user.id) %><% if user.rank == 2 %> admin<% elsif user.rank == 1 %> moderator <% end %> </h2>
		<% temp = 0 %>
		<h4 style="margin-left: 1em">likes: <%= temp %></h4>
		<% i = i + 1 %>
	<% end %>
  </section>
</article>
<br>

app/views/table_mmr/index.html.erb
<h1><article class="head">Table mmr</article></h1>

<%= render 'user', users_have_posts: @users.joins(:posts).group('id').order('SUM(count_like) desc' ), users_have_not_posts: @users.left_outer_joins(:posts).group('users.id').having('count(posts) = 0') %>